//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenGeoDB.Core.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("OpenGeoDB.Core.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string DetailPage_Title {
            get {
                return ResourceManager.GetString("DetailPage_Title", resourceCulture);
            }
        }
        
        internal static string LocationGroupingToZipCodeTextConverter_And {
            get {
                return ResourceManager.GetString("LocationGroupingToZipCodeTextConverter_And", resourceCulture);
            }
        }
        
        internal static string MainPage_Title {
            get {
                return ResourceManager.GetString("MainPage_Title", resourceCulture);
            }
        }
        
        internal static string ChooseZipPage_Title {
            get {
                return ResourceManager.GetString("ChooseZipPage_Title", resourceCulture);
            }
        }
        
        internal static string DistanceType_Kilometers_Text {
            get {
                return ResourceManager.GetString("DistanceType_Kilometers_Text", resourceCulture);
            }
        }
        
        internal static string DistanceType_NauticalMiles_Text {
            get {
                return ResourceManager.GetString("DistanceType_NauticalMiles_Text", resourceCulture);
            }
        }
        
        internal static string DistanceType_Miles_Text {
            get {
                return ResourceManager.GetString("DistanceType_Miles_Text", resourceCulture);
            }
        }
        
        internal static string SettingsPage_Title {
            get {
                return ResourceManager.GetString("SettingsPage_Title", resourceCulture);
            }
        }
        
        internal static string TableSection_Settings {
            get {
                return ResourceManager.GetString("TableSection_Settings", resourceCulture);
            }
        }
        
        internal static string TableSection_Legal {
            get {
                return ResourceManager.GetString("TableSection_Legal", resourceCulture);
            }
        }
        
        internal static string ViewCell_OrderByZipCode {
            get {
                return ResourceManager.GetString("ViewCell_OrderByZipCode", resourceCulture);
            }
        }
        
        internal static string ViewCell_NearbyMarkerCount {
            get {
                return ResourceManager.GetString("ViewCell_NearbyMarkerCount", resourceCulture);
            }
        }
        
        internal static string ViewCell_DistanceType {
            get {
                return ResourceManager.GetString("ViewCell_DistanceType", resourceCulture);
            }
        }
        
        internal static string ViewCell_UsedSoftware {
            get {
                return ResourceManager.GetString("ViewCell_UsedSoftware", resourceCulture);
            }
        }
        
        internal static string ViewCell_PrivacyPolicy {
            get {
                return ResourceManager.GetString("ViewCell_PrivacyPolicy", resourceCulture);
            }
        }
        
        internal static string ViewCell_Imprint {
            get {
                return ResourceManager.GetString("ViewCell_Imprint", resourceCulture);
            }
        }
        
        internal static string DistanceTypeConverter_Kilometers {
            get {
                return ResourceManager.GetString("DistanceTypeConverter_Kilometers", resourceCulture);
            }
        }
        
        internal static string DistanceTypeConverter_NauticalMiles {
            get {
                return ResourceManager.GetString("DistanceTypeConverter_NauticalMiles", resourceCulture);
            }
        }
        
        internal static string DistanceTypeConverter_Miles {
            get {
                return ResourceManager.GetString("DistanceTypeConverter_Miles", resourceCulture);
            }
        }
        
        internal static string UsedSoftwarePage_Title {
            get {
                return ResourceManager.GetString("UsedSoftwarePage_Title", resourceCulture);
            }
        }
        
        internal static string ViewCell_ShowZipCodeAboveNearbyMarker {
            get {
                return ResourceManager.GetString("ViewCell_ShowZipCodeAboveNearbyMarker", resourceCulture);
            }
        }
        
        internal static string Imprint_Content {
            get {
                return ResourceManager.GetString("Imprint_Content", resourceCulture);
            }
        }
        
        internal static string PrivacyPolicy_Content {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Content", resourceCulture);
            }
        }
        
        internal static string SearchBar_Placeholder {
            get {
                return ResourceManager.GetString("SearchBar_Placeholder", resourceCulture);
            }
        }
        
        internal static string ProgressDialog_Loading {
            get {
                return ResourceManager.GetString("ProgressDialog_Loading", resourceCulture);
            }
        }
    }
}
