//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenGeoDB.Core.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenGeoDB.Core.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose ZIP.
        /// </summary>
        internal static string ChooseZipPage_Title {
            get {
                return ResourceManager.GetString("ChooseZipPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string DetailPage_Title {
            get {
                return ResourceManager.GetString("DetailPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:F2} km.
        /// </summary>
        internal static string DistanceType_Kilometers_Text {
            get {
                return ResourceManager.GetString("DistanceType_Kilometers_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:F2} mi..
        /// </summary>
        internal static string DistanceType_Miles_Text {
            get {
                return ResourceManager.GetString("DistanceType_Miles_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:F2} NM.
        /// </summary>
        internal static string DistanceType_NauticalMiles_Text {
            get {
                return ResourceManager.GetString("DistanceType_NauticalMiles_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometers.
        /// </summary>
        internal static string DistanceTypeConverter_Kilometers {
            get {
                return ResourceManager.GetString("DistanceTypeConverter_Kilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miles.
        /// </summary>
        internal static string DistanceTypeConverter_Miles {
            get {
                return ResourceManager.GetString("DistanceTypeConverter_Miles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nautical Miles.
        /// </summary>
        internal static string DistanceTypeConverter_NauticalMiles {
            get {
                return ResourceManager.GetString("DistanceTypeConverter_NauticalMiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;utf-8&quot;&gt;
        ///	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot;&gt; 
        ///	&lt;title&gt;Imprint&lt;/title&gt; 
        ///	&lt;style&gt;
        ///		body{font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; padding:1em; background-color: #fff; color: #000;}
        ///	&lt;/style&gt;
        ///&lt;/head&gt; 
        ///&lt;body&gt;
        ///	&lt;h1&gt;Legal Disclosure&lt;/h1&gt;
        ///	Information in accordance with section &amp;sect;5 TMG&lt;br/&gt;
        ///	&lt;br/&gt;
        ///	Sebastian Kruse&lt;br/&gt;
        ///	Beriner Ring 1a&lt;br/&gt;
        ///	31600 Uchte&lt;br/&gt;
        ///	Germany&lt;br /&gt;
        ///
        ///	&lt;h2&gt;Contact&lt;/h2&gt;
        ///	Telephone: +49 (0) 5763 7949127&lt;br/&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Imprint_Content {
            get {
                return ResourceManager.GetString("Imprint_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  and.
        /// </summary>
        internal static string LocationGroupingToZipCodeTextConverter_And {
            get {
                return ResourceManager.GetString("LocationGroupingToZipCodeTextConverter_And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        internal static string MainPage_Title {
            get {
                return ResourceManager.GetString("MainPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt; 
        ///&lt;head&gt; 
        ///  &lt;meta charset=&quot;utf-8&quot;&gt; 
        ///  &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot;&gt; 
        ///  &lt;title&gt;Privacy Policy&lt;/title&gt; 
        ///  &lt;style&gt;
        ///    body{font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; padding:1em; background-color: #fff; color: #000;}
        ///  &lt;/style&gt;
        ///&lt;/head&gt; 
        ///&lt;body&gt;
        ///  &lt;h2&gt;Privacy Policy&lt;/h2&gt; 
        ///  &lt;p&gt; 
        ///    Sebastian Kruse built the application PLZ Suche (the &quot;App&quot;) with ad support. This App is provided by Sebastian Kruse at no cost and is intended for use as is.
        ///  &lt;/p&gt; 
        ///  &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PrivacyPolicy_Content {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchBar_Placeholder {
            get {
                return ResourceManager.GetString("SearchBar_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsPage_Title {
            get {
                return ResourceManager.GetString("SettingsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal.
        /// </summary>
        internal static string TableSection_Legal {
            get {
                return ResourceManager.GetString("TableSection_Legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string TableSection_Settings {
            get {
                return ResourceManager.GetString("TableSection_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used Software.
        /// </summary>
        internal static string UsedSoftwarePage_Title {
            get {
                return ResourceManager.GetString("UsedSoftwarePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit of length.
        /// </summary>
        internal static string ViewCell_DistanceType {
            get {
                return ResourceManager.GetString("ViewCell_DistanceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprint.
        /// </summary>
        internal static string ViewCell_Imprint {
            get {
                return ResourceManager.GetString("ViewCell_Imprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearby marker count.
        /// </summary>
        internal static string ViewCell_NearbyMarkerCount {
            get {
                return ResourceManager.GetString("ViewCell_NearbyMarkerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order by ZIP Code.
        /// </summary>
        internal static string ViewCell_OrderByZipCode {
            get {
                return ResourceManager.GetString("ViewCell_OrderByZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string ViewCell_PrivacyPolicy {
            get {
                return ResourceManager.GetString("ViewCell_PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show ZIP above marker.
        /// </summary>
        internal static string ViewCell_ShowZipCodeAboveNearbyMarker {
            get {
                return ResourceManager.GetString("ViewCell_ShowZipCodeAboveNearbyMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used Software.
        /// </summary>
        internal static string ViewCell_UsedSoftware {
            get {
                return ResourceManager.GetString("ViewCell_UsedSoftware", resourceCulture);
            }
        }
    }
}
