// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace OpenGeoDB.Core.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("OpenGeoDB.Core.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string DetailPage_Title {
            get {
                return ResourceManager.GetString("DetailPage_Title", resourceCulture);
            }
        }
        
        internal static string LocationGroupingToZipCodeTextConverter_And {
            get {
                return ResourceManager.GetString("LocationGroupingToZipCodeTextConverter_And", resourceCulture);
            }
        }
        
        internal static string MainPage_Title {
            get {
                return ResourceManager.GetString("MainPage_Title", resourceCulture);
            }
        }
        
        internal static string ChooseZipPage_Title {
            get {
                return ResourceManager.GetString("ChooseZipPage_Title", resourceCulture);
            }
        }
        
        internal static string DistanceType_Kilometers_Text {
            get {
                return ResourceManager.GetString("DistanceType_Kilometers_Text", resourceCulture);
            }
        }
        
        internal static string DistanceType_NauticalMiles_Text {
            get {
                return ResourceManager.GetString("DistanceType_NauticalMiles_Text", resourceCulture);
            }
        }
        
        internal static string DistanceType_Miles_Text {
            get {
                return ResourceManager.GetString("DistanceType_Miles_Text", resourceCulture);
            }
        }
    }
}
